name: BarcodeCaptureViewsSample
description: Demonstrates the various ways to best integrate the scanner into the UI of your app.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scandit_flutter_datacapture_barcode:
    ^6.7.1
  permission_handler: ^5.1.0+2
  flutter_platform_widgets: 0.70.2
  cupertino_icons: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
